# Generated by Django 4.1.3 on 2022-11-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_added_zip_to_address'),
    ]

    operations = [
        migrations.RunSQL("""
        INSERT INTO store_collection(title)
        VALUES('collection1')
         """,
         """ 
         DELETE FROM  store_collection
        WHERE title='collection1'
         """
         )
    ]
